name: user_articles
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  flutter_bloc: ^8.0.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  retrofit: ^4.1.0
  bloc: ^8.0.1 

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true
